name: CI
on: [push]
jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [
          '3.6',
          '3.9',
          '3.10.0-beta.2',
        ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Setup package
      run: python -m pip install -e .[dev]
    - name: Generate coverage report
      run: |
        python -m pytest --cov=./ --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true
