name: CI
on:
  pull_request:
    paths-ignore:
    - gallery/**
    - README.md
  push:
    branches:
    - main
  workflow_dispatch:

concurrency:
  # auto-cancel any in-progress job *on the same branch*
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-tests:
    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        python-version:
        - '3.10'
        - '3.11'
        - '3.12'
        - 3.13-dev
        include:
        - os: macos-latest
          python-version: '3.12'
        - os: windows-latest
          python-version: '3.12'

    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout Source
      uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Build
      # installing in editable mode to allow coverage + src layout
      run: |
        python -m pip install --upgrade pip
        python -m pip install --editable .
        python -m pip install --requirement requirements/tests.txt

    - name: Test
      run: |
        python -m pip freeze
        python -m coverage run -m pytest --color=yes

    - name: Upload coverage data
      uses: actions/upload-artifact@v4
      with:
        name: wxc_coverage_data-${{ matrix.os }}-${{ matrix.python-version }}
        path: .coverage.*
        if-no-files-found: ignore
        include-hidden-files: true

  coverage:
    name: Combine & check coverage
    runs-on: ubuntu-latest
    needs: unit-tests

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        # Use latest Python, so it understands all syntax.
        python-version: 3.x

    - run: python -m pip install --upgrade coverage[toml]

    - uses: actions/download-artifact@v4
      with:
        pattern: wxc_coverage_data-*
        merge-multiple: true

    - name: Check coverage
      run: |
        python -m coverage combine
        python -m coverage html --skip-covered --skip-empty
        python -m coverage report --fail-under=95

    - name: Upload HTML report if check failed.
      uses: actions/upload-artifact@v4
      with:
        name: wxc_coverage_report
        path: htmlcov
      if: ${{ failure() }}

  type-check:
    runs-on: ubuntu-latest
    name: type check
    strategy:
      matrix:
        os:
        - ubuntu-latest
        python-version:
        # Match minimal supported Python version
        # to make sure we're not using unparseable syntax,
        # and also run on the most recent version possible to make sure
        # the code typechecks also there
        - '3.10'
        - '3.12'

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Build
      run: |
        python -m pip install --upgrade pip
        python -m pip install .
        python -m pip install --requirement requirements/typecheck.txt

    - name: Run mypy
      run: mypy src/wxc
