name: type checking

on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - README.md

jobs:
  build:
    runs-on: ubuntu-latest
    name: mypy
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Build
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install ".[typecheck]"

    - name: Run mypy
      run: mypy wxc
